---
title: "R Notebook - Project Team 1"
---
```{r Explorative Data Analysis}
library(dplyr)
# Data Import
ph <- read.csv("/Users/yhjnthn/Documents/USD_MS-ADS/ADS506/project/get_it_done_pothole_requests_datasd_v1.csv")
# Changing date_requested format to Date format
ph$date <- as.Date(ph$date_requested)
# Number of rows
count(ph) # There are 26590 cases in the data set.

# Data Summary
summary(ph)
```

Investigating most common areas that require repairs, we will look at zip codes, council_district, and comm_plan_code for the investigation.

```{r zip code}
# Zip Code Count
ph %>% count(zipcode, sort = TRUE)

# Histogram
library(ggplot2)
ggplot(ph) +
  geom_bar(mapping = aes(zipcode))
```

The 10 most common areas that require repair are zipcodes 92126, 92117, 92111, 92037, 92104, 92115, 92103, 92128, 92101, and 92105.

```{r council_district}
ph %>% count(council_district, sort = TRUE)

# Histogram
ggplot(ph) +
  geom_bar(mapping = aes(council_district))
```

The most common council districts that require repairs are 6, 3, 2, 9, 1, 7, 5, 4, and 8, in decreasing order.

```{r comm_plan_code}
ph %>% count(comm_plan_code, sort = TRUE)

# Histogram
ggplot(ph) +
  geom_bar(mapping = aes(comm_plan_code))
```

The 10 most common community plan codes that require repairs are 6, 15, 56, 42, 20, 10, 50, 28, 57, and 31.

```{r}
# Aggregating by date
ph2 <- aggregate(ph$service_request_id, by=list(ph$date), FUN=length)
names(ph2)[1] = "date"
names(ph2)[2] = "count"

# Grouping my month
ph3 <- mutate(ph2, month = format(date, "%Y-%m"))

# Aggregating my date
ph4 <- aggregate.data.frame(ph3, by = list(ph3$month), FUN = length)

# subsetting into relevant months
ph5 <- ph4[11:58,]

# Time Series Creation
ph_ts <- ts(ph5$count, start = c(2018, 12), end = c(2022, 10), frequency = 12)

# Time Series plot graph
plot(ph_ts)
```